# Generated by Django 4.2.5 on 2023-10-01 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('price_unit', models.CharField(choices=[('KG', 'kg'), ('TON', 't'), ('G', 'g'), ('MG', 'mg'), ('LB', 'lb'), ('OZ', 'oz'), ('L', 'l'), ('KL', 'kl'), ('ML', 'ml'), ('PCS', 'pcs')], max_length=4)),
                ('yesterday_price', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('stock_unit', models.CharField(choices=[('KG', 'kg'), ('TON', 't'), ('G', 'g'), ('MG', 'mg'), ('LB', 'lb'), ('OZ', 'oz'), ('L', 'l'), ('KL', 'kl'), ('ML', 'ml'), ('PCS', 'pcs')], max_length=4)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('short_description', models.CharField(max_length=300)),
                ('long_description', models.CharField(max_length=8024)),
            ],
        ),
    ]
