# Generated by Django 4.2.5 on 2023-10-01 17:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_item_date_alter_news_long_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='date',
            field=models.DateField(default=datetime.date(2023, 10, 2)),
        ),
        migrations.AlterField(
            model_name='item',
            name='yesterday_price',
            field=models.IntegerField(null=True),
        ),
    ]
